### ISSUE TITLE
JDBM as InMemory Database

### ISSUE THREAD

**Issue by rajeshonweb** [jankotek/JDBM3#27]
Dear Team,

I found that JDBM gives good performance.
Is it possible to simultaneously access data with two different threads(One Thread inserting data into database) and the other thread retriveing the data and updating the retrieved data?

In simple i need to access the same database using two different threads at the same time.
I need a sample for the same...

**Comment by jankotek** [comment]
Hi,

first: JDBM has in memory mode, just pass null argument instead of file. All changes are of course lost after JVM exits.

   DB db = new DBMaker(null).build();

secondly: JDBM and its collections should be thread safe. But this is not very well tested and there are probably bugs. Also JDBM is synchronized on single lock, so it may not scale that well with concurrent access. 

I personally would investigate 'CuncurrentSkipListMap' first. Guava also have some good stuff.
